adding specfem3d and pysep apps
tapis-project/application-repository pull request #29
Opened 2024-01-17 23:13 UTC by jthet

2024-01-19 22:48 UTC, nathandf requested changes
Regarding the review requests I left about the 'allocation ' scheduler option and container image prop, duplicate that effort for all 4 files.

2024-01-19 22:48 UTC, nathandf commented on pysep/job.json
> +      }
Set "arg" prop to be empty string
Also maybe, we should git rid of it? Up to you

2024-01-19 22:48 UTC, nathandf commented on pysep/app.json
> +  "containerImage": "docker://jthet/pysep:latest",
I think we should change this to have the value of the official scoped docker hub repo. If one doesn't exist, let's get with Ian and see what we can do. If that's not feasible, then leave as is.

2024-01-26 15:06 UTC, jthet reviewed
made changes

2024-01-26 15:17 UTC, nathandf approved these changes

2024-01-26 15:17 UTC, merged